#!/usr/bin/env python3
"""
=============================================================================
 Resting State: Real vs Synthetic EEG — Comprehensive Comparison
=============================================================================

Compares GAN-generated synthetic EEG with real data from the GIPSA-lab
Alpha Waves Dataset across multiple dimensions:

  1. PSD comparison (full spectrum, alpha band highlighted)
  2. Topoplots of alpha-band power distribution
  3. Alpha power bar charts (real vs synthetic, per channel)
  4. Grand average temporal waveforms
  5. Cross-group comparisons (Young vs Elderly, Pre vs Post)

Data layout expected:
  Real data:
    <RS_DATA_ROOT>/Young/S01/rs1o_S01.easy  (pre, eyes-open)
    <RS_DATA_ROOT>/Young/S01/rs1c_S01.easy  (pre, eyes-closed)
    <RS_DATA_ROOT>/Elderly/S01/...
    etc.

  Synthetic data (generated by nbase.py):
    results_RS/pre/Subject_1/synthetic_S1.mat   (Young S1)
    ...
    results_RS/pre/Subject_12/synthetic_S12.mat (Young S12)
    results_RS/pre/Subject_13/synthetic_S13.mat (Elderly S1)
    ...
    results_RS/pre/Subject_22/synthetic_S22.mat (Elderly S10)
    results_RS/post/Subject_1/synthetic_S1.mat
    ...

Usage:
    python rs_comparison.py

    Edit the CONFIGURATION section below to match your paths.

=============================================================================
"""

import os
import sys
import glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import Normalize
from scipy.signal import welch, butter, filtfilt, decimate, iirnotch
from scipy.io import loadmat
import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning)

# Try importing MNE for topoplots (optional but recommended)
try:
    import mne
    HAS_MNE = True
except ImportError:
    HAS_MNE = False
    print("WARNING: MNE not installed. Topoplots will use fallback bar charts.")
    print("  Install with: pip install mne")


# =============================================================================
# CONFIGURATION  —  Edit these to match your setup
# =============================================================================

# ── Paths ────────────────────────────────────────────────────────────────────
RS_DATA_ROOT    = 'data/rs'              # Parent of Young/ and Elderly/ folders
RESULTS_ROOT    = 'results/rs'     # Contains pre/ and post/ subfolders
OUTPUT_DIR      = 'rs_comparison_plots'

# ── Dataset structure ────────────────────────────────────────────────────────
CONDITIONS      = ['pre', 'post']
GROUPS          = ['Young', 'Elderly']
# Subject indices in results_RS (1-based): Young = 1-12, Elderly = 13-22
YOUNG_IDS       = list(range(1, 13))    # Subject_1 through Subject_12
ELDERLY_IDS     = list(range(13, 23))   # Subject_13 through Subject_22

# ── Signal parameters (must match nbase.py RS config) ────────────────────────
NATIVE_FS       = 500              # Original sampling rate of .easy files
GAN_FS          = 125              # Effective fs after decimation (500 / 4)
DECIMATE_FACTOR = 4                # gan_downsample_factor from config
LOWCUT          = 2.0              # Bandpass low (Hz)
HIGHCUT         = 40.0             # Bandpass high (Hz)
EPOCH_S         = 2.0              # Epoch length in seconds
STRIDE_S        = 2.0              # Stride (= epoch_s for non-overlapping)
DURATION_S      = 150.0            # Duration to load per file (seconds)
MARKER_VAL      = 5                # Start marker value in .easy files
ARTIFACT_THRESH = 150.0            # µV peak-to-peak threshold
POWERLINE_HZ    = 50.0             # Powerline notch (50 Hz for UK/EU)
N_CHANNELS      = 8                # Number of EEG channels used

# ── Class labels ─────────────────────────────────────────────────────────────
LABEL_OPEN      = 1
LABEL_CLOSED    = 2

# ── Channel names ───
# UPDATE THESE to match your actual electrode layout from the .easy files.
CH_NAMES = ['Fp1', 'Fp2', 'C3', 'Cz', 'C4', 'P3', 'P4', 'Oz']

# ── Analysis parameters ─────────────────────────────────────────────────────
ALPHA_BAND      = (8, 13)          # Alpha frequency range (Hz)
THETA_BAND      = (4, 8)
BETA_BAND       = (13, 30)
PSD_NPERSEG     = 256              # Welch segment length (at GAN_FS)
PSD_FMAX        = 45               # Max frequency to plot

# ── Upsampling artifact correction ──────────────────────────────────────────
# Conv1DTranspose(k=4, s=2) produces spectral spikes at fs/(2^n).
# For 3 layers at 125 Hz: 15.625 Hz and 31.25 Hz.
# strength=0.0 disables; 0.5 removes ~half the spike; 1.0 full notch (dips).
ARTIFACT_STRENGTH   = 0.3          # Recommended: 0.5
N_UPSAMPLE_LAYERS   = 3            # Number of stride-2 transposed conv layers


# =============================================================================
# 1.  DATA LOADING — Real Data
# =============================================================================

def attenuate_upsample_artifacts(x, gan_fs=GAN_FS, n_layers=N_UPSAMPLE_LAYERS,
                                  strength=ARTIFACT_STRENGTH):
    """
    Attenuate known Conv1DTranspose(k=4, s=2) spectral artifacts.

    The spike is EXCESS energy on top of real spectral content at
    deterministic frequencies: gan_fs / (2^n) for each layer.
    Blending the notched signal with the original removes the excess
    without creating a dip:
        x_out = strength * x_notched + (1 - strength) * x_original

    Applied to synthetic data during comparison only (not during GAN
    training or evaluation) — analogous to powerline noise removal
    in real EEG acquisition pipelines.

    x : (samples, channels, trials) — denormalized synthetic data in µV
    """
    if strength <= 0.0:
        return x

    nyq = gan_fs / 2.0
    artifact_freqs = []
    for layer in range(1, n_layers):
        f_art = gan_fs / (2 ** (n_layers - layer + 1))
        if 1.0 < f_art < nyq - 1.0:
            artifact_freqs.append(f_art)

    if not artifact_freqs:
        return x

    x_clean = np.copy(x)
    for f_notch in artifact_freqs:
        b, a = iirnotch(f_notch, Q=30, fs=gan_fs)
        for t in range(x_clean.shape[2]):        # trials
            for c in range(x_clean.shape[1]):    # channels
                notched = filtfilt(b, a, x_clean[:, c, t])
                x_clean[:, c, t] = strength * notched + (1 - strength) * x_clean[:, c, t]

    return x_clean

def _find_marker_column(raw_array, marker_val, n_eeg_ch):
    """Find the column containing the start marker (scan from right)."""
    n_cols = raw_array.shape[1]
    for col in range(n_cols - 1, max(n_cols - 6, n_eeg_ch), -1):
        if marker_val in raw_array[:, col]:
            return col
    for col in range(n_eeg_ch, n_cols):
        if marker_val in raw_array[:, col]:
            return col
    return -1


def load_and_filter_easy(filepath):
    """
    Load a single .easy file and apply the same preprocessing as nbase.py:
      1. Load text file
      2. Find marker column, slice from start marker
      3. Unit conversion (nV -> µV if needed)
      4. Powerline notch (50 Hz + 100 Hz harmonic)
      5. Butterworth bandpass (2-40 Hz, order 4)

    Returns: (n_samples, n_channels) at NATIVE_FS, or None on failure.
    """
    try:
        raw = np.loadtxt(filepath)
    except Exception as e:
        print(f"    Cannot read {filepath}: {e}")
        return None

    if raw.shape[1] <= N_CHANNELS:
        return None

    mc = _find_marker_column(raw, MARKER_VAL, N_CHANNELS)
    if mc == -1:
        return None

    starts = np.where(raw[:, mc] == MARKER_VAL)[0]
    if len(starts) == 0:
        return None
    si = starts[0]

    n_sam = int(NATIVE_FS * DURATION_S)
    eeg = raw[si:si + n_sam, :N_CHANNELS] if si + n_sam <= len(raw) else raw[si:, :N_CHANNELS]

    if eeg.shape[0] < int(0.5 * n_sam):
        return None

    # Unit conversion
    if np.median(np.abs(eeg)) > 500:
        eeg = eeg / 1000.0

    eeg = eeg.astype(np.float64)

    # Powerline notch (50 Hz + harmonic at 100 Hz)
    if POWERLINE_HZ > 0:
        for freq in [POWERLINE_HZ, POWERLINE_HZ * 2]:
            if freq < NATIVE_FS / 2:
                b_n, a_n = iirnotch(freq, Q=30, fs=NATIVE_FS)
                eeg = filtfilt(b_n, a_n, eeg, axis=0)

    # Bandpass
    nyq = 0.5 * NATIVE_FS
    lo = max(1e-6, min(LOWCUT / nyq, 1 - 1e-6))
    hi = max(1e-6, min(HIGHCUT / nyq, 1 - 1e-6))
    b, a = butter(4, [lo, hi], btype='band')
    filtered = filtfilt(b, a, eeg, axis=0)

    return filtered


def epoch_and_reject(continuous, label):
    """
    Epoch continuous data into fixed-length segments with artifact rejection.
    Returns: x (samples, channels, n_epochs), y (n_epochs,)
    """
    n_samples = continuous.shape[0]
    epoch_len = int(EPOCH_S * NATIVE_FS)
    stride    = int(STRIDE_S * NATIVE_FS)

    epochs = []
    for start in range(0, n_samples - epoch_len + 1, stride):
        ep = continuous[start:start + epoch_len, :]    # (epoch_len, n_ch)
        # Artifact rejection: peak-to-peak per channel
        ptp = np.max(ep, axis=0) - np.min(ep, axis=0)
        if np.any(ptp > ARTIFACT_THRESH):
            continue
        epochs.append(ep)

    if not epochs:
        return np.empty((epoch_len, N_CHANNELS, 0)), np.array([])

    x = np.array(epochs).transpose(1, 2, 0)  # (samples, channels, n_epochs)
    y = np.full(x.shape[2], label)
    return x, y


def decimate_trials(x, factor):
    """
    Anti-aliased decimation along time axis (axis=0).
    x: (samples, channels, trials) -> (samples//factor, channels, trials)
    """
    S, C, T = x.shape
    out_S = S // factor
    out = np.zeros((out_S, C, T), dtype=x.dtype)
    for t in range(T):
        for c in range(C):
            dec = decimate(x[:, c, t].astype(np.float64), factor,
                           ftype='fir', zero_phase=True)
            out[:, c, t] = dec[:out_S]
    return out


def load_real_group(session, group):
    """
    Load all real data for one group (Young or Elderly), one session (pre or post).

    Returns dict:
      {
        'open':   (samples_dec, channels, total_open_epochs)  in µV at GAN_FS,
        'closed': (samples_dec, channels, total_closed_epochs) in µV at GAN_FS,
        'n_subjects': int
      }
    """
    op_pat = 'rs1o' if session == 'pre' else 'rs2o'
    cl_pat = 'rs1c' if session == 'pre' else 'rs2c'

    gdir = os.path.join(RS_DATA_ROOT, group)
    if not os.path.isdir(gdir):
        print(f"  WARNING: directory not found: {gdir}")
        return None

    sub_dirs = sorted(d for d in glob.glob(os.path.join(gdir, '*'))
                      if os.path.isdir(d))

    all_open, all_closed = [], []
    n_subj = 0

    for sd in sub_dirs:
        files = glob.glob(os.path.join(sd, '*.easy'))
        subj_open, subj_closed = [], []

        for fp in files:
            fn = os.path.basename(fp).lower()
            if op_pat in fn:
                cond = 'open'
            elif cl_pat in fn:
                cond = 'closed'
            else:
                continue

            continuous = load_and_filter_easy(fp)
            if continuous is None:
                continue

            lv = LABEL_OPEN if cond == 'open' else LABEL_CLOSED
            x, y = epoch_and_reject(continuous, lv)
            if x.shape[2] == 0:
                continue

            # Decimate to GAN_FS
            x_dec = decimate_trials(x, DECIMATE_FACTOR)

            if cond == 'open':
                subj_open.append(x_dec)
            else:
                subj_closed.append(x_dec)

        if subj_open and subj_closed:
            n_subj += 1
            all_open.extend(subj_open)
            all_closed.extend(subj_closed)

    if not all_open or not all_closed:
        return None

    x_open   = np.concatenate(all_open, axis=2)
    x_closed = np.concatenate(all_closed, axis=2)

    print(f"  Real [{group}/{session}]: {n_subj} subjects, "
          f"open={x_open.shape[2]} epochs, closed={x_closed.shape[2]} epochs")

    return {'open': x_open, 'closed': x_closed, 'n_subjects': n_subj}


# =============================================================================
# 2.  DATA LOADING — Synthetic Data
# =============================================================================

def load_synthetic_group(session, subject_ids):
    """
    Load and denormalize synthetic data for a set of subject IDs.

    Each subject's .mat file contains:
      synthetic_x : (trials, channels, T) in [-1, 1]
      synthetic_y : (trials,) class labels
      norm_method : 'minmax' (for RS)
      norm_global_min, norm_global_max : scalar denorm params

    Returns dict:
      {
        'open':   (samples, channels, total_open_epochs) in µV at GAN_FS,
        'closed': (samples, channels, total_closed_epochs) in µV at GAN_FS,
        'n_subjects': int
      }
    """
    all_open, all_closed = [], []
    n_subj = 0

    for sid in subject_ids:
        mat_path = os.path.join(RESULTS_ROOT, session,
                                f'Subject_{sid}', f'synthetic_S{sid}.mat')
        if not os.path.exists(mat_path):
            print(f"    Synthetic not found: {mat_path}")
            continue

        mat = loadmat(mat_path)
        x_norm = mat['synthetic_x']         # (trials, channels, T) in [-1,1]
        y      = mat['synthetic_y'].ravel()  # (trials,)
        method = str(mat['norm_method'][0]) if 'norm_method' in mat else 'minmax'

        # Denormalize to µV
        if method == 'minmax':
            g_min = float(mat['norm_global_min'])
            g_max = float(mat['norm_global_max'])
            g_range = g_max - g_min
            x_uv = (x_norm + 1.0) / 2.0 * g_range + g_min
        else:
            ch_mean = mat['norm_ch_mean']
            ch_std  = mat['norm_ch_std']
            clip_sigma = float(mat.get('norm_clip_sigma', 3.0))
            x_uv = x_norm * clip_sigma * ch_std + ch_mean

        # x_uv is (trials, channels, T).
        # Convert to (samples, channels, trials) for consistency with real data.
        x_uv = x_uv.transpose(2, 1, 0)   # (T, channels, trials)

        mask_open   = (y == LABEL_OPEN)
        mask_closed = (y == LABEL_CLOSED)

        if mask_open.any():
            all_open.append(x_uv[:, :, mask_open])
        if mask_closed.any():
            all_closed.append(x_uv[:, :, mask_closed])
        n_subj += 1

    if not all_open or not all_closed:
        return None

    x_open   = np.concatenate(all_open, axis=2)
    x_closed = np.concatenate(all_closed, axis=2)

    # Attenuate Conv1DTranspose upsampling artifacts (partial notch)
    if ARTIFACT_STRENGTH > 0:
        x_open   = attenuate_upsample_artifacts(x_open)
        x_closed = attenuate_upsample_artifacts(x_closed)

    print(f"  Synth [{session}]: {n_subj} subjects, "
          f"open={x_open.shape[2]} epochs, closed={x_closed.shape[2]} epochs"
          + (f"  (artifact atten={ARTIFACT_STRENGTH})" if ARTIFACT_STRENGTH > 0 else ""))

    return {'open': x_open, 'closed': x_closed, 'n_subjects': n_subj}


def match_epoch_counts(real_data, synth_data):
    """
    Subsample the larger set (real or synthetic) to match the smaller set.
    This ensures fair comparison with equal trial counts.
    Returns copies with matched sizes.
    """
    out = {}
    for state in ['open', 'closed']:
        nr = real_data[state].shape[2]
        ns = synth_data[state].shape[2]
        n = min(nr, ns)
        # Random subsample from whichever is larger
        rng = np.random.default_rng(42)
        r_idx = rng.choice(nr, n, replace=False) if nr > n else np.arange(nr)
        s_idx = rng.choice(ns, n, replace=False) if ns > n else np.arange(ns)
        out[state] = {
            'real':  real_data[state][:, :, r_idx],
            'synth': synth_data[state][:, :, s_idx],
            'n': n,
        }
    return out


def apply_global_power_correction(matched_data):
    """
    Apply a single global RMS amplitude correction to synthetic data to
    compensate for systematic tanh activation range compression.

    One scalar computed from ALL real and synthetic data pooled together.
    No per-channel, per-frequency, or per-condition fitting.
    """
    real_all  = np.concatenate([matched_data[s]['real']  for s in ['open', 'closed']], axis=2)
    synth_all = np.concatenate([matched_data[s]['synth'] for s in ['open', 'closed']], axis=2)

    rms_real  = np.sqrt(np.mean(real_all ** 2))
    rms_synth = np.sqrt(np.mean(synth_all ** 2))

    if rms_synth < 1e-10:
        return matched_data, 1.0

    gain = rms_real / rms_synth
    for state in ['open', 'closed']:
        matched_data[state]['synth'] = matched_data[state]['synth'] * gain

    return matched_data, gain


# =============================================================================
# 3.  ANALYSIS FUNCTIONS
# =============================================================================

def compute_psd(x, fs=GAN_FS, nperseg=PSD_NPERSEG):
    """
    Compute average PSD across all trials and channels.
    x: (samples, channels, trials)
    Returns: freqs, psd_mean (averaged over trials), psd_per_ch (channels,freqs)
    """
    S, C, T = x.shape
    all_psd = []
    for t in range(T):
        ch_psd = []
        for c in range(C):
            f, p = welch(x[:, c, t], fs=fs, nperseg=min(nperseg, S))
            ch_psd.append(p)
        all_psd.append(ch_psd)

    # (trials, channels, freq_bins)
    all_psd = np.array(all_psd)
    psd_per_ch = np.mean(all_psd, axis=0)    # (channels, freq_bins)
    psd_mean   = np.mean(psd_per_ch, axis=0)  # (freq_bins,)
    psd_sem    = np.std(np.mean(all_psd, axis=1), axis=0) / np.sqrt(T)

    return f, psd_mean, psd_sem, psd_per_ch


def compute_band_power(x, fs=GAN_FS, band=ALPHA_BAND, nperseg=PSD_NPERSEG):
    """
    Compute average band power per channel across all trials.
    x: (samples, channels, trials)
    Returns: (channels,) array of mean log band power.
    """
    S, C, T = x.shape
    bp = np.zeros((C, T))
    for t in range(T):
        for c in range(C):
            f, p = welch(x[:, c, t], fs=fs, nperseg=min(nperseg, S))
            mask = (f >= band[0]) & (f <= band[1])
            bp[c, t] = np.log(np.mean(p[mask]) + 1e-10) if mask.any() else 0.
    return np.mean(bp, axis=1), np.std(bp, axis=1) / np.sqrt(T)


def compute_grand_average(x):
    """
    Grand average waveform across all trials, per channel.
    x: (samples, channels, trials)
    Returns: mean (samples, channels), sem (samples, channels)
    """
    mean = np.mean(x, axis=2)
    sem  = np.std(x, axis=2) / np.sqrt(x.shape[2])
    return mean, sem


# =============================================================================
# 4.  PLOTTING FUNCTIONS
# =============================================================================

REAL_COLOR  = '#2166AC'   # Blue
SYNTH_COLOR = '#B2182B'   # Red
OPEN_COLOR  = '#4DAF4A'   # Green
CLOSE_COLOR = '#984EA3'   # Purple
YOUNG_COLOR = '#FF7F00'   # Orange
ELDER_COLOR = '#377EB8'   # Blue


def plot_psd_comparison(matched_data, title, save_path):
    """
    Side-by-side PSD for eyes-open and eyes-closed.
    Shows full spectrum with alpha band shaded.
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 6), sharey=True)

    for ax, state, state_label in zip(axes, ['open', 'closed'],
                                       ['Eyes Open', 'Eyes Closed']):
        x_r = matched_data[state]['real']
        x_s = matched_data[state]['synth']

        f_r, psd_r, sem_r, _ = compute_psd(x_r)
        f_s, psd_s, sem_s, _ = compute_psd(x_s)

        # Plot in dB
        psd_r_db = 10 * np.log10(psd_r + 1e-15)
        psd_s_db = 10 * np.log10(psd_s + 1e-15)
        sem_r_db = 10 * sem_r / (psd_r * np.log(10) + 1e-15)
        sem_s_db = 10 * sem_s / (psd_s * np.log(10) + 1e-15)

        mask = f_r <= PSD_FMAX
        ax.fill_between(f_r[mask], psd_r_db[mask] - sem_r_db[mask],
                         psd_r_db[mask] + sem_r_db[mask],
                         alpha=0.2, color=REAL_COLOR)
        ax.plot(f_r[mask], psd_r_db[mask], color=REAL_COLOR, lw=2,
                label=f'Real (n={x_r.shape[2]})')

        ax.fill_between(f_s[mask], psd_s_db[mask] - sem_s_db[mask],
                         psd_s_db[mask] + sem_s_db[mask],
                         alpha=0.2, color=SYNTH_COLOR)
        ax.plot(f_s[mask], psd_s_db[mask], color=SYNTH_COLOR, lw=2,
                label=f'Synthetic (n={x_s.shape[2]})')

        # Shade alpha band
        ax.axvspan(ALPHA_BAND[0], ALPHA_BAND[1], alpha=0.08, color='gold',
                   label=f'Alpha ({ALPHA_BAND[0]}-{ALPHA_BAND[1]} Hz)')

        ax.set_xlabel('Frequency (Hz)', fontsize=12)
        ax.set_title(state_label, fontsize=14)
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)
        ax.set_xlim([0, PSD_FMAX])

    axes[0].set_ylabel('PSD (dB µV²/Hz)', fontsize=12)
    fig.suptitle(title, fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_alpha_topomap(matched_data, title, save_path):
    """
    Topoplot of alpha band power for real vs synthetic, open vs closed.
    Uses MNE's built-in topoplot functionality natively. 
    Falls back to a standard bar chart if MNE is not available.
    """
    panels = [
        (0, 0, 'open',   'real',  'Real — Eyes Open'),
        (0, 1, 'open',   'synth', 'Synthetic — Eyes Open'),
        (1, 0, 'closed', 'real',  'Real — Eyes Closed'),
        (1, 1, 'closed', 'synth', 'Synthetic — Eyes Closed'),
    ]

    # Compute all alpha powers first for consistent colour scale across all 4 subplots
    bp_dict = {}
    all_bp = []
    for r, c, state, source, label in panels:
        x = matched_data[state][source]
        bp_mean, bp_sem = compute_band_power(x, band=ALPHA_BAND)
        bp_dict[(state, source)] = (bp_mean, bp_sem)
        all_bp.append(bp_mean)

    all_bp = np.array(all_bp)
    vmin, vmax = all_bp.min(), all_bp.max()

    if HAS_MNE:
        # Create MNE info with standard 10-20 positions
        info = mne.create_info(ch_names=CH_NAMES[:N_CHANNELS],
                               sfreq=GAN_FS, ch_types='eeg')
        montage = mne.channels.make_standard_montage('standard_1020')
        info.set_montage(montage, on_missing='warn')

        fig, axes = plt.subplots(2, 2, figsize=(10, 8))
        
        # FIX: 
        # 1. extrapolate='head' fills the whole head circle smoothly (removes the hexagon).
        # 2. sphere=(0.0, 0.0, 0.0, 0.095) locks the scaling to the standard head size, 
        #    keeping Fp1, Fp2, and Oz properly inside the head outline.
        kwargs_topo = dict(
            show=False, 
            cmap='RdYlBu_r', 
            vlim=(vmin, vmax), 
            extrapolate='head', 
            sphere=(0.0, 0.0, 0.0, 0.095)
        )

        # Row 0: Eyes Open (Real vs Synthetic)
        mne.viz.plot_topomap(bp_dict[('open', 'real')][0], info, axes=axes[0, 0], **kwargs_topo)
        im_open, _ = mne.viz.plot_topomap(bp_dict[('open', 'synth')][0], info, axes=axes[0, 1], **kwargs_topo)
        axes[0, 0].set_title("Real — Eyes Open", fontsize=12)
        axes[0, 1].set_title("Synthetic — Eyes Open", fontsize=12)
        fig.colorbar(im_open, ax=axes[0, :].ravel().tolist(), fraction=0.03, pad=0.04, label="Log Alpha Power (µV²)")

        # Row 1: Eyes Closed (Real vs Synthetic)
        mne.viz.plot_topomap(bp_dict[('closed', 'real')][0], info, axes=axes[1, 0], **kwargs_topo)
        im_closed, _ = mne.viz.plot_topomap(bp_dict[('closed', 'synth')][0], info, axes=axes[1, 1], **kwargs_topo)
        axes[1, 0].set_title("Real — Eyes Closed", fontsize=12)
        axes[1, 1].set_title("Synthetic — Eyes Closed", fontsize=12)
        fig.colorbar(im_closed, ax=axes[1, :].ravel().tolist(), fraction=0.03, pad=0.04, label="Log Alpha Power (µV²)")

        fig.suptitle(title, fontsize=16, fontweight='bold')
        
        # Adjust layout so suptitle doesn't overlap with the topoplots
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        fig.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f"    Saved: {save_path}")

    else:
        # Fallback: bar chart per channel
        fig, axes = plt.subplots(2, 2, figsize=(10, 8))
        x_pos = np.arange(N_CHANNELS)
        
        for r, c, state, source, label in panels:
            ax = axes[r, c]
            bp_mean, bp_sem = bp_dict[(state, source)]
            color = REAL_COLOR if source == 'real' else SYNTH_COLOR
            ax.bar(x_pos, bp_mean, yerr=bp_sem, color=color, alpha=0.7,
                   capsize=3, edgecolor='black', linewidth=0.5)
            ax.set_xticks(x_pos)
            ax.set_xticklabels(CH_NAMES[:N_CHANNELS], fontsize=9)
            ax.set_ylabel('Log Alpha Power', fontsize=10)
            ax.set_title(label, fontsize=11)
            ax.set_ylim(vmin - 0.5, vmax + 0.5)
            ax.grid(True, alpha=0.3, axis='y')

        fig.suptitle(title, fontsize=14, fontweight='bold')
        plt.tight_layout()
        fig.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f"    Saved: {save_path}")


def plot_alpha_bar_comparison(matched_data, title, save_path):
    """
    Bar chart: real vs synthetic alpha power per channel,
    side-by-side for open and closed.
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 6), sharey=True)
    x_pos = np.arange(N_CHANNELS)
    bar_w = 0.35

    for ax, state, state_label in zip(axes, ['open', 'closed'],
                                       ['Eyes Open', 'Eyes Closed']):
        x_r = matched_data[state]['real']
        x_s = matched_data[state]['synth']

        bp_r, sem_r = compute_band_power(x_r, band=ALPHA_BAND)
        bp_s, sem_s = compute_band_power(x_s, band=ALPHA_BAND)

        ax.bar(x_pos - bar_w/2, bp_r, bar_w, yerr=sem_r,
               color=REAL_COLOR, alpha=0.8, capsize=3,
               label=f'Real (n={x_r.shape[2]})', edgecolor='black', linewidth=0.5)
        ax.bar(x_pos + bar_w/2, bp_s, bar_w, yerr=sem_s,
               color=SYNTH_COLOR, alpha=0.8, capsize=3,
               label=f'Synthetic (n={x_s.shape[2]})', edgecolor='black', linewidth=0.5)

        ax.set_xticks(x_pos)
        ax.set_xticklabels(CH_NAMES[:N_CHANNELS], fontsize=10)
        ax.set_title(state_label, fontsize=14)
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3, axis='y')

    axes[0].set_ylabel('Log Alpha Power (µV²)', fontsize=12)
    fig.suptitle(title, fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_multi_band_comparison(matched_data, state, title, save_path):
    """
    Bar chart comparing theta, alpha, beta power for real vs synthetic.
    """
    bands = {'Theta': THETA_BAND, 'Alpha': ALPHA_BAND, 'Beta': BETA_BAND}
    x_r = matched_data[state]['real']
    x_s = matched_data[state]['synth']

    fig, axes = plt.subplots(1, len(bands), figsize=(6 * len(bands), 5), sharey=True)

    for ax, (band_name, band_range) in zip(axes, bands.items()):
        bp_r, sem_r = compute_band_power(x_r, band=band_range)
        bp_s, sem_s = compute_band_power(x_s, band=band_range)

        x_pos = np.arange(N_CHANNELS)
        bar_w = 0.35
        ax.bar(x_pos - bar_w/2, bp_r, bar_w, yerr=sem_r,
               color=REAL_COLOR, alpha=0.8, capsize=3, label='Real',
               edgecolor='black', linewidth=0.5)
        ax.bar(x_pos + bar_w/2, bp_s, bar_w, yerr=sem_s,
               color=SYNTH_COLOR, alpha=0.8, capsize=3, label='Synthetic',
               edgecolor='black', linewidth=0.5)

        ax.set_xticks(x_pos)
        ax.set_xticklabels(CH_NAMES[:N_CHANNELS], fontsize=9)
        ax.set_title(f'{band_name} ({band_range[0]}-{band_range[1]} Hz)', fontsize=12)
        ax.grid(True, alpha=0.3, axis='y')
        if ax == axes[0]:
            ax.set_ylabel('Log Band Power (µV²)', fontsize=11)
            ax.legend(fontsize=10)

    fig.suptitle(title, fontsize=14, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_grand_average(matched_data, ch_idx, title, save_path):
    """
    Grand average waveform at a specific channel for real vs synthetic.
    """
    fig, axes = plt.subplots(1, 2, figsize=(16, 5), sharey=True)
    t_axis = np.arange(matched_data['open']['real'].shape[0]) / GAN_FS

    for ax, state, state_label in zip(axes, ['open', 'closed'],
                                       ['Eyes Open', 'Eyes Closed']):
        x_r = matched_data[state]['real']
        x_s = matched_data[state]['synth']

        ga_r, sem_r = compute_grand_average(x_r)
        ga_s, sem_s = compute_grand_average(x_s)

        ax.fill_between(t_axis, ga_r[:, ch_idx] - sem_r[:, ch_idx],
                         ga_r[:, ch_idx] + sem_r[:, ch_idx],
                         alpha=0.2, color=REAL_COLOR)
        ax.plot(t_axis, ga_r[:, ch_idx], color=REAL_COLOR, lw=2,
                label=f'Real (n={x_r.shape[2]})')

        ax.fill_between(t_axis, ga_s[:, ch_idx] - sem_s[:, ch_idx],
                         ga_s[:, ch_idx] + sem_s[:, ch_idx],
                         alpha=0.2, color=SYNTH_COLOR)
        ax.plot(t_axis, ga_s[:, ch_idx], color=SYNTH_COLOR, lw=2,
                label=f'Synthetic (n={x_s.shape[2]})')

        ax.set_xlabel('Time (s)', fontsize=12)
        ax.set_title(state_label, fontsize=14)
        ax.legend(fontsize=10)
        ax.grid(True, alpha=0.3)

    ch_name = CH_NAMES[ch_idx] if ch_idx < len(CH_NAMES) else f'Ch{ch_idx}'
    axes[0].set_ylabel(f'Amplitude (µV) — {ch_name}', fontsize=12)
    fig.suptitle(title, fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_open_vs_closed(matched_data, source, title, save_path):
    """
    PSD comparison of eyes-open vs eyes-closed for one source (real or synth).
    Highlights the expected alpha suppression (open < closed in alpha band).
    """
    x_o = matched_data['open'][source]
    x_c = matched_data['closed'][source]

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # Left: PSD overlay
    ax = axes[0]
    f_o, psd_o, sem_o, _ = compute_psd(x_o)
    f_c, psd_c, sem_c, _ = compute_psd(x_c)

    psd_o_db = 10 * np.log10(psd_o + 1e-15)
    psd_c_db = 10 * np.log10(psd_c + 1e-15)
    mask = f_o <= PSD_FMAX

    ax.fill_between(f_o[mask], psd_o_db[mask] - 0.5, psd_o_db[mask] + 0.5,
                     alpha=0.15, color=OPEN_COLOR)
    ax.plot(f_o[mask], psd_o_db[mask], color=OPEN_COLOR, lw=2,
            label=f'Eyes Open (n={x_o.shape[2]})')

    ax.fill_between(f_c[mask], psd_c_db[mask] - 0.5, psd_c_db[mask] + 0.5,
                     alpha=0.15, color=CLOSE_COLOR)
    ax.plot(f_c[mask], psd_c_db[mask], color=CLOSE_COLOR, lw=2,
            label=f'Eyes Closed (n={x_c.shape[2]})')

    ax.axvspan(ALPHA_BAND[0], ALPHA_BAND[1], alpha=0.08, color='gold',
               label='Alpha Band')
    ax.set_xlabel('Frequency (Hz)', fontsize=12)
    ax.set_ylabel('PSD (dB µV²/Hz)', fontsize=12)
    ax.set_title('PSD: Open vs Closed', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, PSD_FMAX])

    # Right: Alpha power per channel
    ax = axes[1]
    bp_o, sem_o = compute_band_power(x_o, band=ALPHA_BAND)
    bp_c, sem_c = compute_band_power(x_c, band=ALPHA_BAND)
    x_pos = np.arange(N_CHANNELS)
    bar_w = 0.35

    ax.bar(x_pos - bar_w/2, bp_o, bar_w, yerr=sem_o,
           color=OPEN_COLOR, alpha=0.8, capsize=3, label='Open',
           edgecolor='black', linewidth=0.5)
    ax.bar(x_pos + bar_w/2, bp_c, bar_w, yerr=sem_c,
           color=CLOSE_COLOR, alpha=0.8, capsize=3, label='Closed',
           edgecolor='black', linewidth=0.5)
    ax.set_xticks(x_pos)
    ax.set_xticklabels(CH_NAMES[:N_CHANNELS], fontsize=10)
    ax.set_ylabel('Log Alpha Power (µV²)', fontsize=12)
    ax.set_title('Alpha Power per Channel', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3, axis='y')

    src_label = 'REAL' if source == 'real' else 'SYNTHETIC'
    fig.suptitle(f'{title} — {src_label}', fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_young_vs_elderly(young_data, elderly_data, source, state,
                           title, save_path):
    """
    Compare Young vs Elderly for a specific source (real/synth) and state.
    """
    x_y = young_data[state][source]
    x_e = elderly_data[state][source]

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # PSD comparison
    ax = axes[0]
    f_y, psd_y, _, _ = compute_psd(x_y)
    f_e, psd_e, _, _ = compute_psd(x_e)

    psd_y_db = 10 * np.log10(psd_y + 1e-15)
    psd_e_db = 10 * np.log10(psd_e + 1e-15)
    mask = f_y <= PSD_FMAX

    ax.plot(f_y[mask], psd_y_db[mask], color=YOUNG_COLOR, lw=2,
            label=f'Young (n={x_y.shape[2]})')
    ax.plot(f_e[mask], psd_e_db[mask], color=ELDER_COLOR, lw=2,
            label=f'Elderly (n={x_e.shape[2]})')
    ax.axvspan(ALPHA_BAND[0], ALPHA_BAND[1], alpha=0.08, color='gold',
               label='Alpha Band')
    ax.set_xlabel('Frequency (Hz)', fontsize=12)
    ax.set_ylabel('PSD (dB µV²/Hz)', fontsize=12)
    ax.set_title('PSD: Young vs Elderly', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0, PSD_FMAX])

    # Alpha power bar chart
    ax = axes[1]
    bp_y, sem_y = compute_band_power(x_y, band=ALPHA_BAND)
    bp_e, sem_e = compute_band_power(x_e, band=ALPHA_BAND)
    x_pos = np.arange(N_CHANNELS)
    bar_w = 0.35

    ax.bar(x_pos - bar_w/2, bp_y, bar_w, yerr=sem_y,
           color=YOUNG_COLOR, alpha=0.8, capsize=3, label='Young',
           edgecolor='black', linewidth=0.5)
    ax.bar(x_pos + bar_w/2, bp_e, bar_w, yerr=sem_e,
           color=ELDER_COLOR, alpha=0.8, capsize=3, label='Elderly',
           edgecolor='black', linewidth=0.5)
    ax.set_xticks(x_pos)
    ax.set_xticklabels(CH_NAMES[:N_CHANNELS], fontsize=10)
    ax.set_ylabel('Log Alpha Power (µV²)', fontsize=12)
    ax.set_title('Alpha Power per Channel', fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3, axis='y')

    src = 'REAL' if source == 'real' else 'SYNTHETIC'
    st  = 'Open' if state == 'open' else 'Closed'
    fig.suptitle(f'{title} — {src}, Eyes {st}', fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


def plot_summary_dashboard(all_data, save_path):
    """
    Single-page dashboard summarising alpha power across all conditions.
    Rows: Young, Elderly.  Cols: Pre Open, Pre Closed, Post Open, Post Closed.
    Each cell: Real vs Synthetic bar for one posterior channel (Oz or last channel).
    """
    # Use posterior channel (last one, typically Oz)
    ch_idx = N_CHANNELS - 1
    ch_name = CH_NAMES[ch_idx] if ch_idx < len(CH_NAMES) else f'Ch{ch_idx}'

    fig, axes = plt.subplots(2, 4, figsize=(20, 8), sharey=True)

    groups = ['Young', 'Elderly']
    for gi, group in enumerate(groups):
        for ci, (cond, state) in enumerate(
            [('pre', 'open'), ('pre', 'closed'),
             ('post', 'open'), ('post', 'closed')]):

            ax = axes[gi][ci]
            key = (group, cond)
            if key not in all_data or all_data[key] is None:
                ax.text(0.5, 0.5, 'No data', ha='center', va='center',
                        transform=ax.transAxes, fontsize=12)
                continue

            matched = all_data[key]
            x_r = matched[state]['real']
            x_s = matched[state]['synth']

            # Alpha power at the selected channel
            bp_r, _ = compute_band_power(x_r, band=ALPHA_BAND)
            bp_s, _ = compute_band_power(x_s, band=ALPHA_BAND)

            bars = ax.bar(['Real', 'Synth'], [bp_r[ch_idx], bp_s[ch_idx]],
                          color=[REAL_COLOR, SYNTH_COLOR], alpha=0.8,
                          edgecolor='black', linewidth=0.5)

            # Add value labels
            for bar, val in zip(bars, [bp_r[ch_idx], bp_s[ch_idx]]):
                ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
                        f'{val:.2f}', ha='center', fontsize=9)

            st_label = 'Open' if state == 'open' else 'Closed'
            ax.set_title(f'{cond.capitalize()} — {st_label}', fontsize=11)
            ax.grid(True, alpha=0.3, axis='y')

        axes[gi][0].set_ylabel(f'{group}\nLog Alpha ({ch_name})', fontsize=11)

    fig.suptitle('Summary: Alpha Power at Posterior Channel — Real vs Synthetic',
                 fontsize=16, fontweight='bold')
    fig.tight_layout()
    fig.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"    Saved: {save_path}")


# =============================================================================
# 5.  MAIN ANALYSIS
# =============================================================================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"\n{'='*70}")
    print(f"  Resting State: Real vs Synthetic EEG Comparison")
    print(f"  Real data root:    {RS_DATA_ROOT}")
    print(f"  Results root:      {RESULTS_ROOT}")
    print(f"  Output:            {OUTPUT_DIR}")
    print(f"  GAN effective fs:  {GAN_FS} Hz  (native {NATIVE_FS} Hz / {DECIMATE_FACTOR})")
    print(f"  Channels ({N_CHANNELS}):    {', '.join(CH_NAMES[:N_CHANNELS])}")
    print(f"  Alpha band:        {ALPHA_BAND[0]}-{ALPHA_BAND[1]} Hz")
    print(f"{'='*70}\n")

    # ── Load all data ────────────────────────────────────────────────────────
    all_matched = {}   # (group, condition) -> matched data dict

    for cond in CONDITIONS:
        cond_dir = os.path.join(OUTPUT_DIR, cond)
        os.makedirs(cond_dir, exist_ok=True)

        print(f"\n── Condition: {cond.upper()} ──")

        for group, subj_ids in [('Young', YOUNG_IDS), ('Elderly', ELDERLY_IDS)]:
            print(f"\n  Loading {group}...")

            # Real data
            real = load_real_group(cond, group)
            if real is None:
                print(f"  WARNING: No real data for {group}/{cond}")
                all_matched[(group, cond)] = None
                continue

            # Synthetic data
            synth = load_synthetic_group(cond, subj_ids)
            if synth is None:
                print(f"  WARNING: No synthetic data for {group}/{cond}")
                all_matched[(group, cond)] = None
                continue

            # Match epoch counts
            matched = match_epoch_counts(real, synth)
            all_matched[(group, cond)] = matched
            print(f"  Matched: open={matched['open']['n']} epochs, "
                  f"closed={matched['closed']['n']} epochs")

            # Global RMS power correction (single scalar, tanh compression)
            matched, gain = apply_global_power_correction(matched)
            print(f"  Power correction: gain = {gain:.4f} "
                  f"({20*np.log10(gain):.1f} dB)")

            # ── Per-group plots ──────────────────────────────────────────────
            group_dir = os.path.join(cond_dir, group)
            os.makedirs(group_dir, exist_ok=True)

            # 1. PSD comparison (real vs synthetic)
            plot_psd_comparison(
                matched,
                f'PSD — {group}, {cond.capitalize()}',
                os.path.join(group_dir, 'psd_real_vs_synth.png'))

            # 2. Alpha topoplots (or fallback bar)
            plot_alpha_topomap(
                matched,
                f'Alpha Power Topography — {group}, {cond.capitalize()}',
                os.path.join(group_dir, 'alpha_topomap.png'))

            # 5. Alpha bar comparison
            plot_alpha_bar_comparison(
                matched,
                f'Alpha Power per Channel — {group}, {cond.capitalize()}',
                os.path.join(group_dir, 'alpha_bar.png'))

            # 6. Multi-band comparison (theta/alpha/beta) — eyes open
            plot_multi_band_comparison(
                matched, 'open',
                f'Band Power (Eyes Open) — {group}, {cond.capitalize()}',
                os.path.join(group_dir, 'multiband_open.png'))

            # 7. Multi-band comparison — eyes closed
            plot_multi_band_comparison(
                matched, 'closed',
                f'Band Power (Eyes Closed) — {group}, {cond.capitalize()}',
                os.path.join(group_dir, 'multiband_closed.png'))

            # 8. Grand average waveform at posterior channel (Oz)
            oz_idx = N_CHANNELS - 1
            plot_grand_average(
                matched, oz_idx,
                f'Grand Average at {CH_NAMES[oz_idx]} — {group}, {cond.capitalize()}',
                os.path.join(group_dir, f'grand_avg_{CH_NAMES[oz_idx]}.png'))

            # 9. Grand average at central channel (Cz = index 3)
            cz_idx = min(3, N_CHANNELS - 1)
            plot_grand_average(
                matched, cz_idx,
                f'Grand Average at {CH_NAMES[cz_idx]} — {group}, {cond.capitalize()}',
                os.path.join(group_dir, f'grand_avg_{CH_NAMES[cz_idx]}.png'))

            # 10. Eyes open vs closed — REAL
            plot_open_vs_closed(
                matched, 'real',
                f'{group}, {cond.capitalize()}',
                os.path.join(group_dir, 'open_vs_closed_real.png'))

            # 11. Eyes open vs closed — SYNTHETIC
            plot_open_vs_closed(
                matched, 'synth',
                f'{group}, {cond.capitalize()}',
                os.path.join(group_dir, 'open_vs_closed_synth.png'))

        # ── Cross-group: Young vs Elderly ────────────────────────────────────
        cross_dir = os.path.join(cond_dir, 'Young_vs_Elderly')
        os.makedirs(cross_dir, exist_ok=True)

        young_m  = all_matched.get(('Young', cond))
        elderly_m = all_matched.get(('Elderly', cond))

        if young_m is not None and elderly_m is not None:
            print(f"\n  Cross-group comparisons: Young vs Elderly ({cond})")

            for source in ['real', 'synth']:
                for state in ['open', 'closed']:
                    src_label = source.capitalize()
                    st_label  = state.capitalize()
                    plot_young_vs_elderly(
                        young_m, elderly_m, source, state,
                        f'Young vs Elderly — {cond.capitalize()}',
                        os.path.join(cross_dir,
                                     f'young_vs_elderly_{source}_{state}.png'))

    # ── Cross-condition: Pre vs Post ─────────────────────────────────────────
    print(f"\n── Cross-condition: Pre vs Post ──")
    prepost_dir = os.path.join(OUTPUT_DIR, 'pre_vs_post')
    os.makedirs(prepost_dir, exist_ok=True)

    for group in GROUPS:
        pre_m  = all_matched.get((group, 'pre'))
        post_m = all_matched.get((group, 'post'))
        if pre_m is None or post_m is None:
            print(f"  Skipping {group} pre vs post (missing data)")
            continue

        print(f"  Pre vs Post for {group}...")
        for source in ['real', 'synth']:
            for state in ['open', 'closed']:
                x_pre  = pre_m[state][source]
                x_post = post_m[state][source]

                f_pre,  psd_pre,  _, _ = compute_psd(x_pre)
                f_post, psd_post, _, _ = compute_psd(x_post)

                fig, ax = plt.subplots(figsize=(10, 5))
                mask = f_pre <= PSD_FMAX
                ax.plot(f_pre[mask],
                        10 * np.log10(psd_pre[mask] + 1e-15),
                        color='#E41A1C', lw=2,
                        label=f'Pre (n={x_pre.shape[2]})')
                ax.plot(f_post[mask],
                        10 * np.log10(psd_post[mask] + 1e-15),
                        color='#377EB8', lw=2,
                        label=f'Post (n={x_post.shape[2]})')
                ax.axvspan(ALPHA_BAND[0], ALPHA_BAND[1], alpha=0.08, color='gold')
                ax.set_xlabel('Frequency (Hz)', fontsize=12)
                ax.set_ylabel('PSD (dB µV²/Hz)', fontsize=12)
                src_label = source.upper()
                st_label  = 'Open' if state == 'open' else 'Closed'
                ax.set_title(f'Pre vs Post — {group}, {src_label}, '
                             f'Eyes {st_label}', fontsize=14)
                ax.legend(fontsize=11)
                ax.grid(True, alpha=0.3)
                ax.set_xlim([0, PSD_FMAX])
                fig.tight_layout()
                fname = f'prepost_{group}_{source}_{state}.png'
                fig.savefig(os.path.join(prepost_dir, fname), dpi=150,
                            bbox_inches='tight')
                plt.close(fig)
                print(f"    Saved: {os.path.join(prepost_dir, fname)}")

    # ── Summary dashboard ────────────────────────────────────────────────────
    print(f"\n── Summary Dashboard ──")
    plot_summary_dashboard(all_matched,
                           os.path.join(OUTPUT_DIR, 'summary_dashboard.png'))

    # ── Print numeric summary ────────────────────────────────────────────────
    print(f"\n{'='*70}")
    print(f"  NUMERIC SUMMARY: Mean Alpha Power at {CH_NAMES[-1]} (Log µV²)")
    print(f"{'='*70}")
    print(f"{'Group':>10} {'Cond':>6} {'State':>7} {'Source':>8} {'AlphaPow':>10}")
    print(f"{'-'*50}")

    for group in GROUPS:
        for cond in CONDITIONS:
            key = (group, cond)
            matched = all_matched.get(key)
            if matched is None:
                continue
            for state in ['open', 'closed']:
                for source in ['real', 'synth']:
                    x = matched[state][source]
                    bp, _ = compute_band_power(x, band=ALPHA_BAND)
                    # Report posterior channel
                    val = bp[N_CHANNELS - 1]
                    print(f'{group:>10} {cond:>6} {state:>7} {source:>8} {val:>10.3f}')

    print(f"\n{'='*70}")
    print(f"  All plots saved to: {OUTPUT_DIR}/")
    total = sum(len(files) for _, _, files in os.walk(OUTPUT_DIR)
                if any(f.endswith('.png') for f in files))
    print(f"  Total figures generated: ~{total}")
    print(f"{'='*70}\n")


if __name__ == '__main__':
    main()